CREATE DATABASE IF NOT EXISTS INOVA_CAMPUS 
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

USE INOVA_CAMPUS;

CREATE TABLE IF NOT EXISTS USERS (
    USE_ID INT NOT NULL AUTO_INCREMENT,
    USE_NOME VARCHAR(255) NOT NULL,
    USE_EMAIL VARCHAR(255) NOT NULL,
    USE_SENHA VARCHAR(255) NOT NULL,
    USE_TELEFONE VARCHAR(14) NOT NULL,
    USE_VENDEDOR INT(1) NOT NULL,
    PRIMARY KEY (USE_ID),
    UNIQUE (USE_EMAIL)
) ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PDT_ID INT NOT NULL AUTO_INCREMENT,
    PDT_NOME VARCHAR(255) NOT NULL,
    PDT_PRECO DECIMAL(5.2) NOT NULL,
    PDT_DESCRICAO VARCHAR(200) NOT NULL,
    PDT_USER INT NOT NULL,
    PRIMARY KEY (PDT_ID),
    FOREIGN KEY (PDT_USER) REFERENCES USERS (USE_ID) ON DELETE CASCADE
) ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_general_ci;

