CREATE DATABASE IF NOT EXISTS INOVA_CAMPUS 
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

USE INOVA_CAMPUS;

CREATE TABLE IF NOT EXISTS USERS (
    USE_ID INT NOT NULL AUTO_INCREMENT,
    USE_NOME VARCHAR(255) NOT NULL,
    USE_EMAIL VARCHAR(255) NOT NULL,
    USE_SENHA VARCHAR(255) NOT NULL,
    USE_TELEFONE VARCHAR(14) NOT NULL,
    USE_VENDEDOR INT(1) NOT NULL,
    PRIMARY KEY (USE_ID),
    UNIQUE (USE_EMAIL)
) ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS POSTS (
    PST_ID INT NOT NULL AUTO_INCREMENT,
    PST_TITULO VARCHAR(255) NOT NULL,
    PST_DESCRICAO VARCHAR(1020) NOT NULL,
    PST_FOTO MEDIUMBLOB NOT NULL,
    PST_USER INT NOT NULL,
    PRIMARY KEY (PST_ID),
    FOREIGN KEY (PST_USER) REFERENCES USERS (USE_ID) ON DELETE CASCADE
) ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4
COLLATE = utf8mb4_general_ci;

